lang = 'zh-CN'
title = '上位机'
file = '文件'
open_file = '打开文件'
trash = '垃圾箱'
close = '关闭'
edit = '编辑'
run = '运行'
cv = '视觉'
radar = '雷达'
vehicle = '车辆'
adas = 'ADAS'
display = '可视化'
display_cv = '视觉'
display_radar = '雷达'
display_vehicle = '车辆'